/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courier.tracking.system;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;
/**
 *
 * @author User
 */
public class CustomerShipmentDetails extends javax.swing.JFrame {
private int shipmentId;
private int userID;
private String loggedInemail;
    public CustomerShipmentDetails(String loggedInemail,int userID,int shipmentId) {
       initComponents();
       this.loggedInemail=loggedInemail;
        this.shipmentId = shipmentId;
        this.userID=userID;
        setExtendedState(SignUp.MAXIMIZED_BOTH);
        displayShipmentDetails();
        reviewButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        reviewButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(242, 101, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Shipment Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 0, 310, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Delivery Date:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 570, 490, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 86, 470, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Shipment ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 130, 470, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Shipment Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 180, 490, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Expected  Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 230, 480, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Driver  Contact:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 280, 470, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Company Contact:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 330, 490, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Weight:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 380, 490, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Type:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 430, 480, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Price:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 470, 500, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Delivery Status:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 520, 500, 40);

        reviewButton.setBackground(new java.awt.Color(0, 0, 0));
        reviewButton.setForeground(new java.awt.Color(255, 255, 255));
        reviewButton.setText(" Give Review");
        reviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reviewButton);
        reviewButton.setBounds(390, 590, 140, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 10, 540, 660);

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(102, 0, 102));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 0, 102));
        jLabel13.setText("Location Details");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(81, 6, 269, 48);

        jLabel14.setBackground(new java.awt.Color(102, 0, 102));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 0, 102));
        jLabel14.setText("Origin Address");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 110, 170, 20);

        jLabel15.setBackground(new java.awt.Color(102, 0, 102));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 0, 102));
        jLabel15.setText("Address:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(100, 150, 344, 25);

        jLabel16.setBackground(new java.awt.Color(102, 0, 102));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 0, 102));
        jLabel16.setText("City:");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(100, 200, 344, 25);

        jLabel17.setBackground(new java.awt.Color(102, 0, 102));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 0, 102));
        jLabel17.setText("State:");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(100, 250, 344, 25);

        jLabel18.setBackground(new java.awt.Color(102, 0, 102));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 0, 102));
        jLabel18.setText("Pincode:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(100, 290, 344, 25);

        jLabel19.setBackground(new java.awt.Color(102, 0, 102));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 102));
        jLabel19.setText("Destination Address");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 370, 200, 20);

        jLabel20.setBackground(new java.awt.Color(102, 0, 102));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 102));
        jLabel20.setText("Address:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(110, 410, 344, 25);

        jLabel21.setBackground(new java.awt.Color(102, 0, 102));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 102));
        jLabel21.setText("City:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(110, 460, 344, 25);

        jLabel22.setBackground(new java.awt.Color(102, 0, 102));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 102));
        jLabel22.setText("State:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(110, 500, 344, 25);

        jLabel23.setBackground(new java.awt.Color(102, 0, 102));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 102));
        jLabel23.setText("Pincode:");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(110, 550, 344, 25);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(710, 10, 470, 660);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 13, 80, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/courier/tracking/system/IMAGES/icons8-refresh-30.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1200, 10, 50, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("jButton3");
        jPanel2.add(jButton3);

        jButton4.setText("jButton4");
        jPanel2.add(jButton4);

        jButton5.setText("jButton5");
        jPanel2.add(jButton5);

        jButton6.setText("jButton6");
        jPanel2.add(jButton6);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -60, 1570, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  java.awt.EventQueue.invokeLater(() -> {
        new Cwelcome(loggedInemail).setVisible(true);
         dispose();
    });        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        displayShipmentDetails();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void reviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewButtonActionPerformed
       openReviewFrame();
    }//GEN-LAST:event_reviewButtonActionPerformed
  private void displayShipmentDetails() {
        try {
            // Establish database connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/courier_db", "root", "SHRU@04");

            // Fetch shipment details
            String query = "SELECT u.Fname, u.Lname, s.ShipmentID, s.ShippingDate, s.ExpectedDate, dr.ContactNo, c.Contact, s.Weight, s.Type, p.TotalAmount, d.Status, de.DeliveryDate, lo1.Address AS OriginAddress, lo1.City AS OriginCity, lo1.State AS OriginState, lo1.Pincode AS OriginPincode, lo2.Address AS DestinationAddress, lo2.City AS DestinationCity, lo2.State AS DestinationState, lo2.Pincode AS DestinationPincode "
                         + "FROM shipment s "
                         + "INNER JOIN user u ON s.UserID = u.UserID "
                         + "INNER JOIN delivery d ON s.ShipmentID = d.ShipmentID "
                         + "INNER JOIN payment p ON s.ShipmentID = p.ShipmentID "
                         + "INNER JOIN driver dr ON d.DriverID = dr.DriverID "
                         + "INNER JOIN company c ON s.CompanyID = c.CompanyID "
                         + "INNER JOIN delivery de ON s.ShipmentID = de.ShipmentID "
                         + "INNER JOIN location lo1 ON s.OriginAddressID = lo1.LocationID "
                         + "INNER JOIN location lo2 ON s.DestinationID = lo2.LocationID "
                         + "WHERE s.ShipmentID = ?";
            
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, shipmentId);
            ResultSet rs = pstmt.executeQuery();
            int SID=0;
            if (rs.next()) {
                jLabel3.setText("Username: " + rs.getString("u.Fname") + " " + rs.getString("u.Lname"));
                jLabel4.setText("Shipment ID: " + rs.getInt("s.ShipmentID"));
                jLabel5.setText("Shipment Date: " + rs.getDate("s.ShippingDate"));
                jLabel6.setText("Expected Date: " + rs.getDate("s.ExpectedDate"));
                jLabel7.setText("Driver Contact: " + rs.getString("dr.ContactNo"));
                jLabel8.setText("Company Contact: " + rs.getString("c.Contact"));
                jLabel9.setText("Weight: " + rs.getFloat("s.Weight"));
                jLabel10.setText("Type: " + rs.getString("s.Type"));
                jLabel11.setText("Price: " + rs.getFloat("p.TotalAmount"));
                jLabel12.setText("Delivery Status: " + rs.getString("d.Status"));
                jLabel2.setText("Delivery Date: " + rs.getDate("de.DeliveryDate"));
                jLabel15.setText("Address: " + rs.getString("OriginAddress"));
                jLabel16.setText("City: " + rs.getString("OriginCity"));
                jLabel17.setText("State: " + rs.getString("OriginState"));
                jLabel18.setText("Pincode: " + rs.getString("OriginPincode"));
                jLabel20.setText("Address: " + rs.getString("DestinationAddress"));
                jLabel21.setText("City: " + rs.getString("DestinationCity"));
                jLabel22.setText("State: " + rs.getString("DestinationState"));
                jLabel23.setText("Pincode: " + rs.getString("DestinationPincode"));
                 SID=rs.getInt("s.ShipmentID");
            }
             pstmt.close();
                        System.out.println("1 yes");
                        if (!reviewExists(con, shipmentId)) {
                             System.out.println("2 yes");
            reviewButton.setVisible(true);
            reviewButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Action listener code
                }
            });
            jPanel1.add(reviewButton);
        }
                        System.out.println("3 yes");
            // Close the ResultSet, PreparedStatement, and Connection
            rs.close();
            con.close();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
 private boolean reviewExists(Connection con, int shipmentId) {
    try {
        // Check if a review tuple exists for the shipment
        String query = "SELECT COUNT(*) AS count FROM review WHERE ShipmentID = ?";
        PreparedStatement pstmt = con.prepareStatement(query);
        pstmt.setInt(1, shipmentId);
        ResultSet rs = pstmt.executeQuery();
        System.out.println("r1 yes");
        if (rs.next()) {
            int count = rs.getInt("count");
            System.out.println("r yes");
            return count > 0;
        }

        // Close ResultSet and PreparedStatement
        rs.close();
        pstmt.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    return false; // Default to false if an error occurs
}

     private void openReviewFrame() {
        ReviewPage reviewFrame = new ReviewPage(userID,loggedInemail,shipmentId); // Assuming you have a constructor for ReviewFrame that takes the logged in email
        reviewFrame.setVisible(true);
    }

    /**
     * @param args the command line arguments*/
  
  
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerShipmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerShipmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerShipmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerShipmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton reviewButton;
    // End of variables declaration//GEN-END:variables
}
