/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courier.tracking.system;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
/**
 *
 * @author User
 */
public class Shipment extends javax.swing.JFrame {
public String loggedInemail;
    /**
     * Creates new form Shipment
     */
    public Shipment(String loggedInemail) {
        
        initComponents();
        this.loggedInemail=loggedInemail;
          setExtendedState(Driver.MAXIMIZED_BOTH);
            populateCompanies(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(251, 131, 111));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Fill the shipment details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 40, 290, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Type");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 170, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documents", "Fabric/Cloth", "Shoes", "Devices/Parts" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 170, 160, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Company");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 250, 64, 20);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(220, 240, 160, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Proceed to add location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 490, 250, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Weight(in kg)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 320, 110, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(220, 320, 160, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Available drivers");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 390, 140, 60);

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(220, 400, 160, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(460, 80, 480, 570);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(jButton2)
                .addContainerGap(1275, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jButton2)
                .addContainerGap(667, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-20, 0, 1720, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 private void populateCompanies() {
        try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/courier_db", "root", "SHRU@04");
             Statement stm = connection.createStatement()) {

            String query = "SELECT CompanyName FROM company";
            ResultSet resultSet = stm.executeQuery(query);
            while (resultSet.next()) {
                jComboBox2.addItem(resultSet.getString("CompanyName"));
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

 private void populateDrivers(int companyId) {
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    
    try {
        // Query the database to get the list of drivers for the selected company
        // Replace this with your actual database query logic
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/courier_db", "root", "SHRU@04");
        Statement stm = con.createStatement();
        String query = "SELECT DriverID, Fname FROM driver WHERE CompanyID = " + companyId;
        ResultSet resultSet = stm.executeQuery(query);
        
        // Populate the combo box model with the retrieved drivers
        while (resultSet.next()) {
            int driverId = resultSet.getInt("DriverID");
            String driverName = resultSet.getString("Fname");
            model.addElement(driverId + " - " + driverName);
            System.out.println(driverId+" "+driverName);
        }
        
        // Close the result set, statement, and connection
        resultSet.close();
        stm.close();
        con.close();
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
    
    // Set the combo box model with the populated drivers
    jComboBox3.setModel(model);
}

 
 
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String type = (String) jComboBox1.getSelectedItem();
        String company = (String) jComboBox2.getSelectedItem();
           String weightText = jTextField1.getText().trim(); // Get the text from the weight field

    // Check if weight field is empty
    if (weightText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter the weight.");
        return; // Stop further execution
    }

    float weight;
    try {
        weight = Float.parseFloat(weightText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Weight should be a valid number.");
        return; // Stop further execution
    }
        LocalDate shippingDate = LocalDate.now();
        LocalDate expectedDate = shippingDate.plusDays(7);
           String selectedDriver = (String) jComboBox3.getSelectedItem();
        
        // Assuming you have a method to get the userID from the logged-in user
        int userID = getUserId(loggedInemail); // Replace getUserId() with your actual method to get the userID
        int companyID=getCompanyId(company);
        int driverID = Integer.parseInt(selectedDriver.split(" - ")[0]);
        int ID=0;
        System.out.println(weight);
       if(type!=null && company!=null && weight>0&& selectedDriver!=null){
           
        ID=insertShipment(type, companyID, weight, userID, driverID, shippingDate,expectedDate);
       }else{
            JOptionPane.showMessageDialog(this, "Fill all the fields");
       }
        // Instantiate the next frame (AddLocation) and navigate to it
        
        Addlocation addLocation = new Addlocation(loggedInemail,userID,ID,weight, type, company,driverID);
        addLocation.setVisible(true);
        this.dispose(); //
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String selectedCompany = (String) jComboBox2.getSelectedItem();
    int companyId = getCompanyId(selectedCompany);
    System.out.println(companyId);
    populateDrivers(companyId);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new Cwelcome(loggedInemail).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
public int getCompanyId(String company){
    int CompanyId=-1;
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/courier_db", "root", "SHRU@04");
        Statement stm = con.createStatement();

        // Execute a query to retrieve the user ID
        String query = "SELECT CompanyID FROM company WHERE CompanyName = '" + company + "'";
        ResultSet resultSet = stm.executeQuery(query);
        if (resultSet.next()) {
            // User found, retrieve the user ID from the result set
            CompanyId = resultSet.getInt("CompanyID");
        }

        // Close the result set, statement, and connection
        resultSet.close();
        stm.close();
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
        System.out.println("Error: " + e.getMessage());
    }

    return CompanyId;
}
    public int getUserId(String email) {
    int userId = -1; // Default value if user is not found or error occurs

    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/courier_db", "root", "SHRU@04");
        Statement stm = con.createStatement();

        // Execute a query to retrieve the user ID
        String query = "SELECT UserID FROM user WHERE email = '" + email + "'";
        ResultSet resultSet = stm.executeQuery(query);
        if (resultSet.next()) {
            // User found, retrieve the user ID from the result set
            userId = resultSet.getInt("UserID");
        }

        // Close the result set, statement, and connection
        resultSet.close();
        stm.close();
        con.close();
    } catch (ClassNotFoundException | SQLException e) {
        // Handle any exceptions
        System.out.println("Error: " + e.getMessage());
    }

    return userId;
}

    
    

// Method to insert values into the shipment table
private int insertShipment(String type, int company, float weight, int userID,  int driverID,LocalDate shippingDate,LocalDate expectedDate ) {
    int ID=0;
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/courier_db", "root", "SHRU@04");
        Statement stm = con.createStatement();

        // Assuming your shipment table has columns: Type, Company, Weight, UserID
        String query = "INSERT INTO shipment (Type, CompanyID, Weight, UserID,  ShippingDate, ExpectedDate) " +
                           "VALUES ('" + type + "', '" + company + "', '" + weight + "', '" + userID + "',  '" + shippingDate + "', '" + expectedDate + "')";

        // Execute the insert query
        stm.executeUpdate(query);
                ResultSet rs=stm.executeQuery("select * FROM shipment ORDER BY ShipmentID DESC LIMIT 1");
        rs.next();
         ID=rs.getInt("ShipmentID");
//       int  Sid=int(rs);
        // Close the statement and connection
        stm.close();
        con.close();
         
        
    } catch (Exception e) {
        System.out.println("Error: " + e.getMessage());
    }
   return ID;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
